### ISSUE TITLE
KeyError: 'blackblaze_public_id'というエラーが発生する

### ISSUE THREAD

**Issue by lalalalafo** [Mega-Gorilla/Index_PDF_Translation#1]
config.pyにある環境変数を設定していないためか，エラーが発生します：
```
# ----- 以下 API用 設定 --------
# Black BlazeオブジェクトDB設定
BLACK_BLAZE_CONFIG = {
    'public_key_id': os.environ["blackblaze_public_id"],
    'public_key' : os.environ["blackblaze_public_key"],
    'private_key_id': os.environ["blackblaze_private_id"],
    'private_key' : os.environ["blackblaze_private_key"],
    'public_bucket' : 'pdf-public',
    'private_bucket' : 'pdf-private'
}
```
Black Blazeに登録する必要があるのでしょうか？
エラーメッセージは以下の通りです：
```
(ipt_venv) PS C:\Users\foo\Index_PDF_Translation> python manual_translate_pdf.py
Traceback (most recent call last):
  File "C:\Users\foo\Index_PDF_Translation\manual_translate_pdf.py", line 1, in <module>
    from modules.translate import pdf_translate,PDF_block_check,write_logo_data
  File "C:\Users\foo\Index_PDF_Translation\modules\translate.py", line 3, in <module>
    from config import *
  File "C:\Users\foo\Index_PDF_Translation\config.py", line 11, in <module>
    'public_key_id': os.environ["blackblaze_public_id"],
                     ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'blackblaze_public_id'
```

環境は以下の通りです:
```
Windows 11
conda 24.3.0
Powershell 5.1.22621.2506
```

もし不足がありましたらご指摘ください．
よろしくお願いいたします．

**Comment by Mega-Gorilla** [comment]
確認しました

**Comment by Mega-Gorilla** [comment]
確認しました。
問題は、config.pyにAPI向けの関数設定が挿入サれているため、エラーが発生しておりました。
ローカル翻訳においては、API向けのAPI設定は不要なため、

> BLACK_BLAZE_CONFIG = {
    'public_key_id': os.environ["blackblaze_public_id"],
    'public_key' : os.environ["blackblaze_public_key"],
    'private_key_id': os.environ["blackblaze_private_id"],
    'private_key' : os.environ["blackblaze_private_key"],
    'public_bucket' : 'pdf-public',
    'private_bucket' : 'pdf-private'
}

上記API部分を、別設定ファイル(objective DB config.py)に分離しましたので、最新版をClone頂いてテスト頂ければ幸いです！
